### ISSUE TITLE
how do I disable the links per resource?

### ISSUE THREAD

**Issue by NullVoxPopuli** [joukevandermaas/saule#102]
also, why are they on by default?

**Comment by joukevandermaas** [comment]
Not sure what you mean by 'links per resource'. As far as serializing resources go, there are a few options:

1. The property does not exist: Saule serializes a link
1. The property exists, but is `null`: Saule serializes a link
1. The property exists, and has a value: Saule adds the resource to the `included` hash

If you don't want to serialize links, or want to serialize different ones, you can implement `IUrlPathBuilder`. See the documentation [here](https://github.com/joukevandermaas/saule/wiki/Generating-links). Note that if you return `null` for the relationship links, the link [will not be serialized](https://github.com/joukevandermaas/saule/blob/master/Saule/Serialization/ResourceSerializer.cs#L283).
