### ISSUE TITLE
It looks like only attributes show up in the [FromBody] bodyParams?

### ISSUE THREAD

**Issue by NullVoxPopuli** [joukevandermaas/saule#104]
``` csharp
        public JToken Create([FromBody] JObject bodyParams)
```

I'm trying to send relationship data, and when I inspect the `bodyParams` variable, all I see are the things under attributes. :-\

**Comment by joukevandermaas** [comment]
This should work; see [this](https://github.com/joukevandermaas/saule/blob/master/Tests/Serialization/ResourceDeserializerTests.cs#L60) and [this](https://github.com/joukevandermaas/saule/blob/master/Tests/Serialization/ResourceDeserializerTests.cs#L72) test. Can you provide some more detail, like the request you're trying to deserialize and your resource setup?
