### ISSUE TITLE
Keep JSON formatter

### ISSUE THREAD

**Issue by rhyek** [joukevandermaas/saule#106]
My API needs to have two different types of endpoints where one would return/accept JSON API documents and a second should return simple JSON objects that should be serialized with Json.NET directly (data presented in a complex way that's immediately useful for reports and such on a front-end client). `config.ConfigureJsonApi()` clears all formatters, currently, and this interferes with my intentions.

Is there a way to have both formatters active and use one or the other depending on the `Accept` or `Content-Type` header of the request?

**Comment by rhyek** [comment]
Ok, so I figured out that instead of using `config.ConfigureJsonApi()` I can just do `config.Formatters.Add(new JsonApiMediaTypeFormatter())` (which is deprecated) without first doing `config.Formatters.Clear()` and I get what I want.

Is there any reason why this isn't desirable?

**Comment by joukevandermaas** [comment]
It doesn't fully support all of Saule's features, notably some error handling. This problem is addressed in #101, which will hopefully merge soon.

**Comment by rhyek** [comment]
Awesome. I'll go ahead and close this and subscribe to the pull request. Thank you.
