### ISSUE TITLE
Can't use ExceptionFilter because JsonApiMediaTypeFormatter public constructor is obsolete

### ISSUE THREAD

**Issue by bxh** [joukevandermaas/saule#109]
In [wiki](https://github.com/joukevandermaas/saule/wiki/Customizing-the-serialization-process), there is an example about using `ExceptionFilter` with an instance of `JsonApiMediaTypeFormatter`. But it seems  that the public constructor of `JsonApiMediaTypeFormatter` is marked as obsolete. Could you advise how to define an `ExceptionFilter` with `JsonApiMediaTypeFormatter`?

**Comment by joukevandermaas** [comment]
That example should still work, even though the constructor is obsolete. This was an oversight; the constructor was marked as obsolete to indicate the new way to set up Saule without considering this valid use case for it. Until this is fixed, please add a [`pragma`](http://stackoverflow.com/questions/968293/c-sharp-selectively-suppress-custom-obsolete-warnings) to ignore the warning.
