### ISSUE TITLE
500 error when action returns a simple POCO object and using config.ConfigureJsonApi()

### ISSUE THREAD

**Issue by rhyek** [joukevandermaas/saule#111]
I'm using a local build with the latest source code. This is my action: 
```c#
[Authorize]
[Route("api/usuarios/{id}/parcial")]
public async Task<dynamic> PutPartial(string id, UsuarioPartialPut json) {
    if (id != User.Identity.GetUserId()) {
        throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.Forbidden, Errores.SinAcceso));
    }
    using (var db = new ApplicationDbContext()) {
        var user = await db.Users.Where(u => u.Id == id).SingleOrDefaultAsync();
        if (user == null) {
            return NotFound();
        }
        
        user.Email = json.Email;
        user.Locale = json.Locale;

        await db.SaveChangesAsync();
        return new {
            ok = true
        };
    }
}
```
In my `WebApiConfig.cs`, if I use `config.ConfigureJsonApi()` I will get a 500 http error, but I will still get the JSON payload: `{"ok":true}`.

If I use `config.Formatters.Add(new JsonApiMediaTypeFormatter())` I get the same payload, but no 500 status.

This action isn't meant to use Saule, and the request has header `Accept:application/json, text/javascript, */*; q=0.01`.

**Comment by joukevandermaas** [comment]
I think Saule's [delegating handler](https://github.com/joukevandermaas/saule/blob/master/Saule/Http/PreprocessingDelegatingHandler.cs) still runs, even if the media type is not `application/vnd.api+json`. This is arguably a bug. To work around this you can manually override `PreprocessingDelegatingHandler` and add this behavior, then do the setup in [`ConfigureJsonApi()`](https://github.com/joukevandermaas/saule/blob/master/Saule/Http/HttpConfigExtensions.cs#L51) manually.
