### ISSUE TITLE
Provide abillity to disable json properties with dashes

### ISSUE THREAD

**Issue by Xylotomous** [joukevandermaas/saule#114]
I've been using your very nice library for a prototype API service but have discovered that you've made a number of things serialize with hyphens, e.g., some-property-name as seen here ResourceAttribute.cs. This is seems an odd choice to make as a number of languages do not allow properties with a - in them. Javascript and C# among them. It can be overcome with annotations in libraries such as JSON.NET but it would be nice to have either a boolean to disable or remove it all together rather than the burden of annotating many classes. I also note that it is not a requirement in the JSON API spec ( although it appears in many examples, oddly enough ).

Thanks in advance and for your generous contribution of work to the community.

**Comment by joukevandermaas** [comment]
> This is seems an odd choice to make as a number of languages do not allow properties with a - in them. Javascript and C# among them.

JSON API is a serialization format. It's not meant to be used directly from any language, rather to transfer data between different sides of a network. Saule seamlessly converts between kebab case and the C# conventional pascal case. Ember Data, the most commonly used client-side JSON API library, does the same for JavaScript and camel case. 

Either way, kebab case seems conventional for JSON API. There are many reasons for this default choice that people smarter than me have thought through. Although I'm not completely opposed to introducing other options, I'm hesitant to do so without good reason.

Can you elaborate on why dashes are problematic for you?

**Comment by Xylotomous** [comment]
Hello, apologies for the slow reply. I'm not using the JSON directly, but serializing it via Saule and then on the user end of an API it is deserialized into a given object. 

As a Javascript key it can work with the dash provided the key is i quotes, e.g. var foo =  {"some-key" : "some value"} and accessed as foo["some-key"], but var foo = {some-key : "some value"} is not valid. 

In C# or Java, etc. You can't have a property or field with a dash. Users deserializing the dashed keys will get errors unless measures are taken to translate. There are several means to do so such as shown here: http://stackoverflow.com/questions/14753113/how-to-deserialize-a-property-with-a-dash-in-its-name-with-newtonsoft-jso.

My issue is that users must take extra steps to normalize the hyphenated keys. I have overcome the problem by writing a DelegatingHandler that post-processes the response after Saule has serialized it, removing the hyphen and returning it to the original property form. I don't know why it didn't occur to me until after I opened this issue. I intend to put it up on my GH account here, but would also gladly share it if you were interested. It could then be provided to Saule users who have the same need but not cause work for you!

**Comment by bjornharrtell** [comment]
It's the recommended naming as per http://jsonapi.org/recommendations/#naming, I think it's out of scope to implement anything else directly in Saule.

**Comment by joukevandermaas** [comment]
I tend to agree with @bjornharrtell. However, if this becomes a big need (say, for performance reasons or whatever), I'm open to a PR that addresses this is in a non-intrusive way.

**Comment by Xylotomous** [comment]
This was used on an internal prototype project and we found more cases that we needed behavior not in the library (saule).  We diverged enough that eventually we wrote our own implementation. Thank you for taking time to consider my original request and for making the library.

**Comment by joukevandermaas** [comment]
This has since been implemented.
