### ISSUE TITLE
how to define post, patch and delete operation in the controller 

### ISSUE THREAD

**Issue by dhirajdhakal09** [joukevandermaas/saule#115]
Hi,

I want to define a controller with Update, Insert and Delete methods.  
Setting [HttpPost] will work for insertion, but how do we expose other operations like PUT, PATCH and DELETE?

**Comment by joukevandermaas** [comment]
The same way; `[HttpPut]`, `[HttpPatch]` and `[HttpDelete]`. Please refer to the ASP.Net documentation for this.

**Comment by dhirajdhakal09** [comment]
Thanks.
