### ISSUE TITLE
PreprocessingDelegatingHandler breaks Swashbuckle embedded Swagger UI

### ISSUE THREAD

**Issue by nukefusion** [joukevandermaas/saule#116]
`PreprocessingDelegatingHandler` runs on every single request so requests for non-API resources (such as CSS and JS assets for the Swagger UI) are [rejected with a JsonApiException](https://github.com/joukevandermaas/saule/blob/5e162593848e22c44fef96358c10dba2a62b514f/Saule/Http/PreprocessingDelegatingHandler.cs#L47).

Is there any reason why the handler can't be executed only for requests with an accept header containing the JSON API media type?

**Comment by joukevandermaas** [comment]
This was fixed in #118.
