### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by corfor** [joukevandermaas/saule#12]
Are there plans for supporting [JSON API pagination](http://jsonapi.org/format/#fetching-pagination "pagination")?

**Comment by joukevandermaas** [comment]
Yes, I have thought about it. I think it should work similarly to [odata filtering](http://www.asp.net/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/create-an-odata-v4-endpoint), where you put an attribute on your controller and return `IQueryable`, and the library figures it out. That way we'd support querying, pagination, etc. using a simple API that people are already used to.

As of right now I have no idea how difficult it is to turn those url queries into actual `Expression`s, but I do intend to add this feature.

Do you have any suggestions on how you would like this work from an API creator's point of view?

**Comment by joukevandermaas** [comment]
I decided to move forward with pagination first, and think about more advanced filtering methods later. See #15 for how to use it.
