### ISSUE TITLE
Customized query-able endpoints

### ISSUE THREAD

**Issue by bxh** [joukevandermaas/saule#120]
I'm wondering what the most efficient approach is to support filtering for a server backend that does **not** leverage EF.

Would you consider in future version Saule simply parses query parameters and leave all the filtering work to controller methods?

**Comment by joukevandermaas** [comment]
Yeah, that seems fair. I assume by not using EF you mean you don't return `IQueryable` but you still want the client to influence your DB query? Saule internally already has [`QueryContext`](https://github.com/joukevandermaas/saule/blob/master/Saule/Queries/QueryContext.cs) which should contain most of the info you need to do querying.

To implement this in a good way, that class and the more specific contexts would need to get a more unified API and be made immutable. Then they'd need to be passed into the action method somehow. There'd also need to be a mechanism to disable Saule's own filtering (this could likely just depend on the action method's parameters, or an attribute).

**Comment by joukevandermaas** [comment]
This was mostly implemented in #181 by @sergey-litvinov-work. The only remaining task before this issue can be closed is to document that work.
