### ISSUE TITLE
How does saule return 201 created?

### ISSUE THREAD

**Issue by dhirajdhakal09** [joukevandermaas/saule#122]
Hi,

On creating an entity with POST verb I would expect to get 201 created along with the newly created json response, but it is giving 200 OK instead.

The following is the definition:

        [HttpPost]
        [ReturnsResource(typeof(AddressResource))]
        [Route("api/address")]
        public CustomModel.Address Insert([FromBody] CustomModel.Address address)
        {
         }

Please help me asap.

**Comment by joukevandermaas** [comment]
You can use the regular ASP.Net way of doing this. Saule does not change that.

**Comment by dhirajdhakal09** [comment]
Thanks jouke. :)
