### ISSUE TITLE
Resource model relationships should support an optional 'include' parameter

### ISSUE THREAD

**Issue by goo32** [joukevandermaas/saule#126]
From my understanding Saule currently includes relationships by default. A nice enhancement would be to allow an optional include parameter on the association that would be respected on serialization.

eg.

In resource model...

`BelongsTo<AuthorResource>("Author"); // Default include = true``

Would be serialized to...

```
"relationships": {
  "author": {
    "links": {
      "self": "http://example.com/articles/1/relationships/author",
      "related": "http://example.com/articles/1/author"
    },
   "data": { "type": "people", "id": "9" }
  },
...
"included": [{
  "type": "people",
  "id": "9",
  "attributes": {
    "first-name": "Dan",
    "last-name": "Gebhardt",
    "twitter": "dgeb"
  }

```

While...

`BelongsTo<AuthorResource>("Author", false);``

```
Would be serialized to...

"relationships": {
  "author": {
    "links": {
      "self": "http://example.com/articles/1/relationships/author",
      "related": "http://example.com/articles/1/author"
    }
  },

```

**Comment by joukevandermaas** [comment]
I like this suggestion, and it ties in nicely to what I replied on #125. That said, I don't think a boolean is sufficient. As far as I can see, there are three options:

1. Always include (also if the value is `null` or if the property does not exist on the model)
2. Never include (always serialize a link even if the property has a value)
3. Decide based on the value (a link if `null`, otherwise include it)

The third is the current behavior, and should remain the default.

**Comment by goo32** [comment]
What about something like this?...

```
BelongsTo<AuthorResource>("Author"); // Default behaviour ie. ApiResource.ExcludeIfNull
BelongsTo<AuthorResource>("Author", ApiResource.Include);
BelongsTo<AuthorResource>("Author", ApiResource.Exclude);

```

**Comment by joukevandermaas** [comment]
Yes, I like the idea of an enum, probably named something like `SideLoad` or `Include`. Possible values should be:

1. `IfProvided` (default)
2. `Always`
3. `Never`

**Comment by yohanmishkin** [comment]
Forgive me if I'm miss understanding, but maybe this is best left to be decided by the actual web request using the `include` request parameter?

[See here](http://jsonapi.org/format/#fetching-includes)
