### ISSUE TITLE
"Last" key missing for pagination links

### ISSUE THREAD

**Issue by bxh** [joukevandermaas/saule#127]
While [JSON spec](http://jsonapi.org/format/#fetching-pagination) states that all `first`, `last`, `prev` and `next` keys must exist for pagination links, the current version of Saule does not support it.

**Comment by joukevandermaas** [comment]
The relevant part of the spec says:

>The following keys *MUST* be used for pagination links:
> - `first`: the first page of data
> - `last`: the last page of data
> - `prev`: the previous page of data
> - `next`: the next page of data
>
> Keys *MUST* either be omitted or have a null value to indicate that a particular link is unavailable.

This should be interpreted as: "if you do pagination, do not generate links *other than the above*". Saule omits links it cannot generate (particularly `last`, sometimes `next` and `prev`) without potential performance problems, which is in accordance with the spec.

I'm not opposed to generating those links anyway under certain conditions (maybe based on a flag in the attribute). This would be a performance trade-off that an app developer can decide, but Saule cannot.
