### ISSUE TITLE
Accept page size from pagination query string

### ISSUE THREAD

**Issue by bxh** [joukevandermaas/saule#128]
It's common for a RESTful client to suggest a page such as `?page[number]=0&page[size]=20`. Saule presently can only specify page size on the server side. Can we add support to `page[size]`?

**Comment by erikhejl** [comment]
I'm taking on this work in a fork of ours, but I did have some questions.  I'm puzzled as to why QueryContext properties are assigned both by the Filter/Sorting/Pagination attributes and also by the JsonApiSerializerOfT.   It seems like the latter would be problematic?

**Comment by joukevandermaas** [comment]
@erikhejl `JsonApiSerializer<T>` is can be used in setup. This is relevant for filtering, because you can provide custom filtering logic. I doubt this is relevant to pagination, I think you will only need to care about the non-generic `JsonApiSerializer`.
