### ISSUE TITLE
Saule returns 500 Internal Server Error when request is not following JSON API format

### ISSUE THREAD

**Issue by wojciechrak** [joukevandermaas/saule#133]
**Request**
````
POST /api/v1/articles HTTP/1.1
Host: localhost:8080
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json

{
	"id": 123,
	"name": "test"
}
````

**Response** `Status 500 Internal Server Error`
````
{
  "errors": [
    {
      "title": "You must add a [ReturnsResourceAttribute] to action methods.",
      "detail": "Saule.JsonApiException: You must add a [ReturnsResourceAttribute] to action methods.",
      "code": "Saule.JsonApiException",
      "links": {
        "about": "https://github.com/joukevandermaas/saule/wiki"
      }
    }
  ]
}
````

I just spent fair amount of time scratching my head why Saule doesn't respect my `[ReturnsResource]` attribute on Controller.

But it turns out, that problem is in completely different place.
Of course request body is wrong.

Error message is not only not helpful, but very misleading!
Shouldn't `400` or `406` be returned instead?

**Comment by joukevandermaas** [comment]
Yeah, this is pretty terrible. Nice errors are important.

**Comment by joukevandermaas** [comment]
I published a new pre-release that fixes this problem. I'll try publish a stable release sometime soon.

**Comment by wojciechrak** [comment]
Great, I will try check this out today.
