### ISSUE TITLE
EntityCommandExecutionException when serializing lazy loading EF entity

### ISSUE THREAD

**Issue by bjornharrtell** [joukevandermaas/saule#138]
When using Entity Framework 6 and returning an IQueryable I get an exception message from Newtonsoft.Json like `Error getting value from 'xxx' on 'System.Data.Entity.DynamicProxies.xxxx'`.
at the line:
https://github.com/joukevandermaas/saule/blob/master/Saule/Serialization/ResourceSerializer.cs#L48

The inner exception is a `System.Data.Entity.Core.EntityCommandExecutionException` and says:
"There is already an open DataReader associated with this Command which must be closed first."

This seem to only happen depending on lazy loading state.

**Comment by joukevandermaas** [comment]
Does this error disappear when you disable Saule? It might be something in your app. Either way that line you linked will have to go sometime soon, see #99 and #103.

**Comment by bjornharrtell** [comment]
It seems the error is not caused by Saule as such, it's more an effect of serializing a lazy loading entity. Problem is described here:
http://stackoverflow.com/questions/6062192/there-is-already-an-open-datareader-associated-with-this-command-which-must-be-c

But perhaps this needs consideration in Saule when using IQueryable, so that it will force the inclusion of (selected) related entities before doing the serialization.

**Comment by bjornharrtell** [comment]
Some more useful information here http://stackoverflow.com/questions/38815800/include-property-but-exclude-one-of-that-propertys-properties. Will report back when I settle on the best way to handle this.

**Comment by bjornharrtell** [comment]
As this was most likely not an issue with Saule itself and I won't be investigating it further I'll close it until further notice.
