### ISSUE TITLE
1.6 tracking issue

### ISSUE THREAD

**Issue by joukevandermaas** [joukevandermaas/saule#139]
Before we can release Saule 1.6 (which contains some nice bugfixes and a new feature), the following will need to be done:

- [x] Move the docs to a github pages website, in a `/docs` directory of the main repo. This will make it easier to contribute to the documentation.
- [x] Write documentation for the new including resources feature (see #137)

**Comment by adamalesandro** [comment]
@joukevandermaas I would be interested in handling the `/docs` relocation above if it's still pending.

**Comment by joukevandermaas** [comment]
@adamalesandro it is! If you are able to do it, I'd love your help!

**Comment by adamalesandro** [comment]
OK, I will get started. I have never done this before but I'm sure I can figure it out.
