### ISSUE TITLE
support various http status code 

### ISSUE THREAD

**Issue by luke-zhang** [joukevandermaas/saule#145]
We are looking if a resource can be serialized as JSON API format with various HTTP status code returned to a client, for example, we need to response a user resource with 300 HTTP status code to the client when one of business validations is not passed. we tried this codes, but looks it doesn't work.

[ReturnsResource(typeof(AuthenticateResource))]
public IHttpActionResult CreateSession(UserModel model) {
  return Content(System.Net.HttpStatusCode.Ambiguous, model, new JsonApiMediaTypeFormatter())
}

**Comment by joukevandermaas** [comment]
Can you elaborate on "it doesn't work"? What does happen? As far as I'm aware Saule doesn't mess with status codes outside of what the spec dictates.

**Comment by luke-zhang** [comment]
we saw a 500 internal server error when using the version1.5.1.318, but it works great if we switch to the latest beta version from nuget.

**Comment by joukevandermaas** [comment]
Yeah, I really need to get that release out. I don't want to without docs for all the features tho :smile: (#139 is the tracking issue).

**Comment by joukevandermaas** [comment]
1.6 is released, so this should be resolved.
