### ISSUE TITLE
When I have parameter [FromBody] I get status code 400 no content

### ISSUE THREAD

**Issue by tomasjurasek** [joukevandermaas/saule#166]
#Hi,
I have simple controller method like this:

```
        [HttpPost]
        [Route("test")]
        [ReturnsResource(typeof(TestModelResource))]
        public async Task<TestViewModel> Test([FromBody] TestViewModel model)
        {
            return new TestViewModel();
        }
```

ResourceModel
```
  public class TestModelResource : ApiResource
    {
        public TestModelResource()
        {
            WithId(nameof(TestViewModel.Id));
            Attribute(nameof(TestViewModel.Name));
        }
    }
```

I get **400 status no content**. 
But if I set attribute [FromUri], it works.
Its a bug? I need [FromBody]

Thanks
Tomas

**Comment by tomasjurasek** [comment]
When I set Content-Type: application/vnd.api+json 
![image](https://user-images.githubusercontent.com/1623933/28535540-0aa92a5a-70a5-11e7-835c-702eca210375.png)

**Comment by joukevandermaas** [comment]
I think `[FromBody]` does some weird stuff sometimes. Have you tried without any attribute on the parameter?

**Comment by tomasjurasek** [comment]
I tried it, but the same issue.
Here is screen from swagger:
![image](https://user-images.githubusercontent.com/1623933/28538132-74697e38-70ad-11e7-9a18-b441c728b0be.png)

**Comment by joukevandermaas** [comment]
But that is *not* valid JSON API content. It should be like:

```json
{
  "data": {
    "id": "22",
    "type": "mymodel",
    "attributes": {
      "name": "string"
    }
  }
}
```
