### ISSUE TITLE
I can't call method for upload Files

### ISSUE THREAD

**Issue by tomasjurasek** [joukevandermaas/saule#167]
Hi,
I have classic method for upload files.
` public async Task<IHttpActionResult> UploadFile(){......}`
[UploadFile](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/sending-html-form-data-part-2)

But when I use [ReturnsResource(typeof(GlobalFileModelResource))] doesnt works. 
![image](https://user-images.githubusercontent.com/1623933/28591686-dca7de98-7186-11e7-84c4-efb82f14f44d.png)

It is some specific settings for IsMimeMultipartContent?

Thanks
Tomas

**Comment by joukevandermaas** [comment]
I think if you use the following overload for `ConfigureJsonApi` it might work:

```csharp
ConfigureJsonApi(
    jsonApiConfiguration: new JsonApiConfiguration(),
    overwriteOtherFormatters: false)
```

If not, that's a bug (in my opinion). Note that to my knowledge, the JSON API spec itself does not mention uploading files and/or multipart content.

**Comment by tomasjurasek** [comment]
Does not works with these options . The same errors.

**Comment by tomasjurasek** [comment]
Im playing with this issue. I think we need overload this method

```
       public static void ConfigureJsonApi(
            this HttpConfiguration config,
            JsonApiConfiguration jsonApiConfiguration,
            bool overwriteOtherFormatters)
        {
            config.MessageHandlers.Add(new PreprocessingDelegatingHandler(jsonApiConfiguration));
            var formatter = new JsonApiMediaTypeFormatter(jsonApiConfiguration);

            if (overwriteOtherFormatters)
            {
                config.Formatters.Clear();
                config.Formatters.Add(formatter);
            }
            else
            {
                config.Formatters.Insert(0, formatter);
            }
        }
```

Because we dont want clear all formatters and insert only one. We need add formatters to end of collection when we want use WEB API together with JSON API. When we rework this method it will be breaking change, overload is better solution.

@joukevandermaas
