### ISSUE TITLE
Cycle Detection

### ISSUE THREAD

**Issue by corfor** [joukevandermaas/saule#18]
In the domain I'm modeling, a Category has many Products and a Product has many Categories.

An infinite loop occurs:
```
        public CategoryResource()
        {
            HasMany<ProductResource>("Products");
        }
```
```
      public ProductResource()
        {
            HasMany<CategoryResource>("Categories");
        }
```

**Comment by joukevandermaas** [comment]
When does the loop occur? As soon as you start the website or when you're actually serializing something?

**Comment by corfor** [comment]
It happened as soon as I started the website.

**Comment by corfor** [comment]
I worked around it by using a reference class (which does not point back to Categories) instead
```
        public CategoryResource()
        {
            HasMany<ProductReferenceResource>("Products","products");
        }
```

**Comment by joukevandermaas** [comment]
Luckily this was pretty straightforward to fix. There should be a new version on nuget shortly.

**Comment by corfor** [comment]
Wonderful! Thank you!
