### ISSUE TITLE
error 406

### ISSUE THREAD

**Issue by barsh** [joukevandermaas/saule#186]
I'm trying to setup a minimal starter project from scratch using Saule and I'm looking for help.

https://github.com/barsh/SauleStarter/issues/1

**Comment by joukevandermaas** [comment]
@barsh Please describe the error you are getting, and what you have tried to do. I don't have access to the repository you linked.

**Comment by barsh** [comment]
@joukevandermaas that repo is public (now it is) and I added you as a collaborator.

**Comment by barsh** [comment]
Thanks to some help from @joukevandermaas, I'm now getting JSON API responses in Chrome.  This info might help others:

I had to upgrade to [Saule 1.7.0.516-beta](https://github.com/barsh/SauleStarter/commit/b992fd277751626a94c25b010b59dc5c937cf4cc) and then [configure Saule like this](https://github.com/barsh/SauleStarter/commit/fe61aeb81c859535be751b0eca61867ad9ffbf82):
`config.ConfigureJsonApi(new JsonApiConfiguration(), overwriteOtherFormatters: true)`
