### ISSUE TITLE
Property names in nested data structrures are kebab-cased even if CamelCasePropertyNameConverter is provided

### ISSUE THREAD

**Issue by Bazaleev** [joukevandermaas/saule#192]
Hi all,

Thanks for the great library. There is an inconsistency in data serialization when we opt in for CamelCase serialization. Root level properties are serialized as expected but all properties in nested data models are kebab-cased. So it looks like this: 
`{
    "data": {
        "type": "table-filter",
        "id": "12",
        "attributes": {
            "isDefault": false,
            "orderBy": {
                "field-name": "Field2",
                "is-descending": true
            },
            "where": [
                {
                    "field-name": "Field1",
                    "condition": "=",
                    "value": "5"
                }
            ]
        }
    },
    "links": {
        "self": "http://example.com/api/people/123"
    }
}`

The issue can be easily fixed if we pass IPropertyNameConverter (provided in ResourceSerializer) to JsonApiContractResolver. 

Thanks!

**Comment by joukevandermaas** [comment]
@Bazaleev Thanks for reporting this! I will create a patch release for this fix: 1.7.1.
