### ISSUE TITLE
Relationships are still kebap case even after supplying CamelCasePropertyNameConverter

### ISSUE THREAD

**Issue by PhyberApex** [joukevandermaas/saule#196]
Imho the relationship names should also be camel case after applying the property name converter!

~Cheers

**Comment by joukevandermaas** [comment]
You're right, this seems like a bug.

**Comment by joukevandermaas** [comment]
@PhyberApex I have fixed this issue. I will publish a pre-release with the fix very soon, and a patch release for 1.7 later today.

**Comment by PhyberApex** [comment]
wow...thank you very much for this! Awesome!

~Cheers
