### ISSUE TITLE
Support for fields filter

### ISSUE THREAD

**Issue by PhyberApex** [joukevandermaas/saule#197]
Hey,

sorry for using an issue for a feature request but I didn't see any option to do a feature request. Do you plan to include the "fields" query parameter as specified by the JSON-API [here](http://jsonapi.org/format/#fetching-sparse-fieldsets)

~Cheers

**Comment by joukevandermaas** [comment]
I'm certainly open to it, I've never had a use for it myself but I can see the value.

**Comment by PhyberApex** [comment]
Closing this as it got done with #199
