### ISSUE TITLE
Nested filters

### ISSUE THREAD

**Issue by PhyberApex** [joukevandermaas/saule#207]
Hey,

sorry to bother you so much but this is something we came about a few times now. We have been using your library quite a lot and there were a few use cases where we needed to implement a filter on a nested attribute. We came up with our own filter query parameter like "customNestedFilter[address.street]=somestreet". But it would be nice to have this as an actual filter. Would you be open for PR for a nested filter with the "." to indicate nesting as it should not be allowed in a property anyways? As filtering is not really specified within the json-api specification we came up with the dot notation.

~Cheers

**Comment by joukevandermaas** [comment]
Are you saying you have a model like this:

```csharp
class Address { string Street { get; set; } }
class Person { Address Address { get; set; } }
```

And you want to filter on the street name? If so, I like the dot notation and I would be all for it. It would make Saule filtering a lot more powerful.

**Comment by PhyberApex** [comment]
Exactly what I am talking about! Good to know you are open for it. I will take a look at this after the multiple filter PR. After which I hopefully have a better understanding of the filtering process, making this one easier to do :)

~Cheers

**Comment by PhyberApex** [comment]
Got this working but I did use the multiple strings PR as code base by accident so I will open this PR after the other one is 100% through.

**Comment by PhyberApex** [comment]
PR is open (#209) and up for review. I will close this as soon as the PR is merged.
