### ISSUE TITLE
Is there a release planned which included fields?

### ISSUE THREAD

**Issue by PhyberApex** [joukevandermaas/saule#214]
Sorry for making an issue out of this but I did not know how to contact you otherwise. Are there any plans on a new release? I am specifically looking for that fields parameter. We have a policy in place which forbids us from using non release libraries in that specific project. Again sorry for posting an issue for this.

~Cheers

**Comment by joukevandermaas** [comment]
Makes sense to create a new release for this, so I did it :smile:. Thanks again for contributing this feature!
