### ISSUE TITLE
Polymorphic models support question

### ISSUE THREAD

**Issue by sergey-litvinov-work** [joukevandermaas/saule#241]
Hi Jouke, hope everything is good on your side. 

we are exploring a possibility to have endpoint that would return different types that inherits the same base abstract model class. For example
```
public abstract class MenuItem
{
	public int Id { get; set; }
}

public class ServiceMenuItem : MenuItem
{
	public string ServiceName { get; set; }
}

public class PackagesMenuItem : MenuItem
{
	public string PackageName { get; set; }
}
```

and then we could have 
```
[HttpGet]
[ReturnsResource(typeof(MenuItemApiResource))]
public IEnumerable<MenuItem> GetMenuItems()
{
...
```

And right now it doesn't work well, as `MenuItemApiResource` knows only about attributes of the base model so we can't return different types. The intention is to get something like this
```
{
    "data": [
        {
            "type": "service-menu-item",
            "id": "21",
            "links": {
                "self": "https://localhost:44300/WebService4/v5/customer/menu-items/21/"
            },
            "attributes": {
                "service-name": "some service"
            },
        },
        {
            "type": "packages-menu-item",
            "id": "42",
            "links": {
                "self": "https://localhost:44300/WebService4/v5/customer/menu-items/42/"
            },
            "attributes": {
                "package-name": "some package"
            }
        }
    ],
    "links": {
        "self": "https://localhost:44300/WebService4/v5/customer/menugroup/4"
    }
```

I can make a PR with the code change for that but wanted to get your opinion before that. We are thinking about two implementation approaches

## Logic in the ApiResource

We can update `ApiResource` to have following changes

```
private Dictionary<Type, Lazy<ApiResource>> _polymorphicTypes = new Dictionary<Type, Lazy<ApiResource>>();

public virtual void AddPolymorphicTypes<ModelType, ResourceType>()
    where ResourceType: ApiResource, new()
{
    if (!_polymorphicTypes.ContainsKey(typeof(ModelType)))
    {
        _polymorphicTypes.Add(typeof(ModelType), new Lazy<ApiResource>(() => new ResourceType()));
    }
}

public virtual ApiResource GetResourceByObject(object model)
{
    if (model == null)
        return this;

    return GetResourceByType(model.GetType());
}

public virtual ApiResource GetResourceByType(Type objectType)
{
    // if type is present, then we return it
    if (objectType != null && _polymorphicTypes.TryGetValue(objectType, out Lazy<ApiResource> apiResource))
        return apiResource.Value;

    // otherwise return current resource
    return this;
}
```
and then we can have such `MenuItemApiResource`
```
internal class MenuItemApiResource: ApiResource
{
	public MenuItemApiResource()
	{
		OfType(nameof(MenuItem).GetTypeFromModelName(false),
			nameof(MenuItem).GetTypeFromModelName(true));
		WithId(nameof(MenuItem.Id));
		
		// This two calls are new one 
		AddPolymorphicTypes<ServiceMenuItem, MenuItemServiceCustomerApiResource>();
		AddPolymorphicTypes<PackagesMenuItem, PackagesMenuItemCustomerApiResource>();
	}
}

internal class MenuItemServiceApiResource: MenuItemApiResource
{
	public MenuItemServiceApiResource()
		: base()
	{
		OfType(nameof(ServiceMenuItem).GetTypeFromModelName(false),
			nameof(ServiceMenuItem).GetTypeFromModelName(true));
		Attribute(nameof(ServiceMenuItem.ServiceName));
	}
}
```

That `AddPolymorphicTypes` is a new thing here, and we can specify types that current resource might have as inherited and we link it to specific type. So when we serialize\deserialize, we can use specific ApiResource based on the model type. And then we can update usages of the ApiResource to be like

```
        public ResourceSerializer(
            object value,
            ApiResource type,
...
        {
            _resource = type.GetResourceObject(value);
```
so instead of storing original `ApiResource type`, we are calling `GetResourceObject` that will return the same instance, or if `ApiResource` supports polymorphic classes, then it might return different `ApiResource`

## Logic in own PolymorphicApiResource: ApiResource

Similar approach but with more clear separation might be to create a new `public abstract class PolymorphicApiResource: ApiResource` that would have all these new methods so the logic would be only in this specific api resource. And we still would need to have some virtual method in the base `ApiResource` that would return `ApiResource` and then we can override it in the new `PolymorphicApiResource` class

Another open question is, in our case we need it to generate a response, so we have serialization case only. But i guess if you fine with that approach, you would want to have deserialization logic as part of the same PR? like if we have Put\Post endpoints that has abstract model, and then based on `type` of the object and linked `ApiResource`, it will create correct model

**Comment by joukevandermaas** [comment]
I think if you set attributes on a resource, that do not have a corresponding property on the model, the serializer will ignore them. In other words, you may be able to just add *all* attributes from both subclasses in the `ApiResource` class and that might work. I realize that may not be very nice, but it might help you get going for now.

I don't like having an explicit relationship (in code) between `ApiResource` and the model, because one of the explicit design goals was to allow many model classes, potentially from third party libraries, to serialize to the same JSON API resource. Saule never relies on specific model classes, it always looks at properties on whatever it gets.

I do like the idea of attributes being "optional" or "conditional" in some ways, especially if this can be done with a lambda or something. It is already possible to dynamically build `ApiResource` classes (by design), so that would hopefully not complicate it too much for the polymorphic case.

Does something like that make sense to you?

**Comment by sergey-litvinov-work** [comment]
Specifying attributes for all model in the same resource might be not so good for us as the main API consumer is Ember application within Ember Data and it supports polymorphic models. Our intention is to have different behavior depending on the model type, so when we return different models based from the same base type - Ember app will render them on the page but each of them might be rendered slightly different depending on the model.type. And if we place everything into one model, then Ember app's code would need some workaround and a bit smelly code.


>I don't like having an explicit relationship (in code) between ApiResource and the model, because one of the explicit design goals was to allow many model classes, potentially from third party libraries, to serialize to the same JSON API resource. Saule never relies on specific model classes, it always looks at properties on whatever it gets.

Yeah, i understand that. in that case we need to understand model so we can determine model correctly so we need that type. It's one way type, so we can have different resources for the same Type model (as it's 1 model to many ApiResource) but yeah, i understand the reasoning

>I do like the idea of attributes being "optional" or "conditional" in some ways, especially if this can be done with a lambda or something. It is already possible to dynamically build ApiResource classes (by design), so that would hopefully not complicate it too much for the polymorphic case.

yeah, in our case we want to have different model type. What if we try to make some mix. Like to introduce following interface

```
public interface IApiResourceProvider
{
  public ApiResource Resolve(HttpRequestMessage request);
  public ApiResource Resolve(HttpRequestMessage request, object dataModel)
}
```

And then we will have a default implementation that would get it `Request.GetJsonApiResource();` in both cases. And then we can override it on our side and update second implementation to resolve different ApiResource depending on the model. So in that way it still won't break old compatibility but would allow use to extend it and add our need on top of it.

I don't like `HttpRequestMessage` in that interface too much as it would give direct dependency, so as other way we can have 

```
public interface IApiResourceProvider
{
  public ApiResource Resolve();
  public ApiResource Resolve(object dataObject)
}
public interface ApiResourceProviderFactory
{
  public IApiResourceProvider Create(HttpRequestMessage request);
}
```
And add it to `JsonApiConfiguration`. Then we can create `IApiResourceProvider` somewhere at the start of pipeline in `PreprocessingDelegatingHandler` so it will be tied to current request and then will be passed as part of SauleContext and other places could use it as is. And then we still would be able to override it and return different `ApiResource` depending on the `dataObject`

**Comment by joukevandermaas** [comment]
I like the idea of the interface a lot, I think it would be a great point of extensibility for those who want to customize this part of Saule. For some projects the current implementation is maybe a bit clunky and verbose, with this interface that allows people to simplify if they want that. Definitely a great solution.

**Comment by sergey-litvinov-work** [comment]
Thanks! i'll make PR with the change this\next week for the review

**Comment by sergey-litvinov-work** [comment]
Closing this one as it was resolved in the linked PR
