### ISSUE TITLE
Canonical relationship self link

### ISSUE THREAD

**Issue by corfor** [joukevandermaas/saule#28]
This doesn't seem correct to me (UrlConstructionTests, line 234):
```
  Assert.Equal("/corporations/456/", job["links"].Value<Uri>("self").AbsolutePath);
```

Shouldn't it be:
```
  Assert.Equal("/people/123/relationships/employer/", job["links"].Value<Uri>("self").AbsolutePath);
```

**Comment by joukevandermaas** [comment]
This test uses the `CanonicalUrlPathBuilder`, which serializes self links as a non-relational url. The assert you put would work for the `DefaultUrlPathBuilder`. See [the documentation](https://github.com/joukevandermaas/saule/wiki/Generating-links) for this.

**Comment by corfor** [comment]
But the `self` link here is for the *relationship*, i.e. this is url to use for adding or removing items from a collection via `PUT` or `DELETE`.  `/corporations/456/` is not the url for managing this person's relationship to the `job`.

**Comment by corfor** [comment]
According to the [JsonApi spec](http://jsonapi.org/format/#fetching-relationships), the url in the `self` link of a relationship MUST fetch ***relationship*** data.  

I feel quite strongly that it is incorrect to return, in this example, a link to the corporation. It **MUST** be a link to the relationship itself between the person and the corporation.

**Comment by corfor** [comment]
See also [http://jsonapi.org/format/#document-resource-object-relationships](http://jsonapi.org/format/#document-resource-object-relationships)

```
self: a link for the relationship itself (a "relationship link"). This link allows the client to directly manipulate the relationship. For example, it would allow a client to remove an author from an article without deleting the people resource itself.
```

**Comment by corfor** [comment]
If anything, the "`related` resource link" should be the url that is modifed in this case to be canonical. NOT the `self` link.

**Comment by joukevandermaas** [comment]
You are arguing to reverse the links generated in the `related` and `self` fields by the `CanonicalUrlPathBuilder`? If not, the behavior you describe is the default as implemented in `DefaultUrlPathBuilder`.

**Comment by joukevandermaas** [comment]
I whipped up my interpretation of your suggestion in the `change-self-paths` branch. Maybe you can take a look and see if this is indeed what you mean?

If so I can make a PR and merge it, since it would follow the spec better.

**Comment by corfor** [comment]
Thank you. This looks correct now.
