### ISSUE TITLE
Could not install package in .NET 4.5 project

### ISSUE THREAD

**Issue by jyoung** [joukevandermaas/saule#49]
Having a bit of trouble installing into a project that targets .NET 4.5. 
I get the following error from the package manager:
> Install-Package : Could not install package 'saule 1.3.0.155-beta'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by joukevandermaas** [comment]
Interesting. I'll take a look later today to see if I can fix this. Do you get the same error with the latest 1.2 release?

**Comment by jyoung** [comment]
Yeah, I have tried it with both the current 1.2 release and the pre-release. 
I am using WebApi 5.2.3 targetFramework net45

**Comment by joukevandermaas** [comment]
I noticed Saule was targeting `4.5.1`, rather than `4.5` proper. This is likely what caused your trouble. The newest prerelease (`1.3.0.163-beta`) should solve this issue for you.

Sorry for the trouble, and thanks for reporting this!

**Comment by jyoung** [comment]
Installed just fine. Thanks for your help!

On Fri, Dec 4, 2015 at 9:33 AM, Jouke van der Maas <notifications@github.com
