### ISSUE TITLE
Returns 200 OK when the client makes a bad request

### ISSUE THREAD

**Issue by joukevandermaas** [joukevandermaas/saule#52]
Saule handles `JsonApiException`s internally, but still returns a `200 OK` response code. This should obviously be `400 Bad Request`.

**Comment by joukevandermaas** [comment]
This will likely require a 'breaking change', in the sense that users will have to add another line to their `Startup.cs`. The alternative is to just rethrow those exceptions, but then you get the useless default `An error has occured` error.

We'll need to figure out how to best communicate this change, so that the impact is as low as possible. I would theoretically prefer to deprecate something to signal it, but I'm not 100% on how to do so.

Either way there needs to be a way for Saule to do all of its setup work itself, so that if this happens again, users don't need to know about it. A likely candidate is an extension method on `HttpConfiguration`.

**Comment by romgapuz** [comment]
saw your changes on this, one question: why did you make the JsonApiException internal? there's no way for the calling code (ie. Controller) to throw this exception.

**Comment by joukevandermaas** [comment]
I don't think there's ever an opportunity for user code to handle this exception, since it's only thrown (and handled) from Saule itself. My default mode is to only make public what I expect user code to interact with. Why would *you* like it to be public? 

I know this was technically a breaking change so I'm open reverting it if there's a good reason.

**Comment by romgapuz** [comment]
I'm with you that the user code will not handle the error, the "handling" of the error is the actual serialization and response return to the API consumer which it does right now. But I think the user code must have control to throw the exception for reasons below:

1) Ability to specify HTTP CODE in the error response. (e.g. if the item for deletion is in-existent then give 404, if authentication failed give 403 forbidden or authorization failure give 401 unauthorized, etc).
2) Perform data validation on API parameters (ie. the uri and post data) and return 400 bad request when data validation fails.
3) Current code always return generic 500 internal server error regardless of the nature of the exception.

I also wanted to inherit from JsonApiException and create custom exception class like NotFoundJsonApiException which throws 404, BadRequestJsonApiException for 400, and so on.

What do you think?

**Comment by joukevandermaas** [comment]
You should already be able to do those things by [throwing `HttpResponseException`](http://www.asp.net/web-api/overview/error-handling/exception-handling#httperror). Saule should preserve 4xx status codes when you do. The examples you give are not really about JSON API, they are related to your own software's implementation and domain. For that reason I don't think they need to be `JsonApiException`s.

I like to stay on existing Web API idioms as much as possible, because it lowers the amount of new things developers need to learn before they can be productive with Saule. There are a few gotchas, but I'm working on reducing those. As such, I think Saule having an exception class that it knows about is useful for Saule, but it should not force this concept on developers. C# and .NET, and to an extend Web API already have a strong error handling system, and I'd rather tap into that.

**Comment by romgapuz** [comment]
I tried throwing HttpResponseException and yes HTTP response code is okay but the content is empty. It should be the serialized json that ErrorSerializer do, conforming to json-api specs.

**Comment by romgapuz** [comment]
I think throwing exception like this would suffice for now:

> throw new HttpResponseException(
>      Request.CreateErrorResponse(HttpStatusCode.NotFound, "Item not found.")
> );

**Comment by joukevandermaas** [comment]
Note that if you return `HttpResponseMessage`, you can also do:

```csharp
return Request.CreateResponse(HttpStatusCode.NotFound, new CustomException("My message"));
```

Which will do the right thing.
