### ISSUE TITLE
Nested includes and compound documents

### ISSUE THREAD

**Issue by jrexdepew** [joukevandermaas/saule#61]
Currently in one of our projects we have a resource that we include all of its relationships to prevent multiple api calls. One of the relationships of the parent resource also has has relationships we would like to include all in one payload. For example let's say I have bars resource that has many beers and each beer has a manufacturer.  In my payload I would like to include all the beers a bar sells and then include the manufacturers inside each beer object.  After running through the code it looks like when processing relationship resources, saule is not also processing that relationships resources recursively even if the object being serialized includes that information. I suspect this may have been due to circular references?  If this is possible and I have something setup incorrectly then let me know.  I am currently on the commute home but when I get home I can provide a code example if needed.  I believe if this isn't currently possible, the method that processes the top level resource in the serializer could be refactored to be called recursively for each included resource.  Please excuse any typos as I am typing this on a phone :(

**Comment by joukevandermaas** [comment]
You are exactly right. When first implementing this I decided not to add this feature for fear of infinite loops.

However I'm pretty sure Saule already checks for circular references, so this should be relatively straightforward to implement.

**Comment by rhyek** [comment]
Hi. Is this feature available in the latest beta NuGet package (saule.1.5.0.305-beta)? Currently running some tests and I'm not getting the nested includes. Thanks.

**Comment by rhyek** [comment]
I just built from source and it's definitely not working. My models look like this:
```
namespace api.Models.Db {
    public class RefreshToken {
        [Key]
        public string Id { get; set; }
        [Required]
        [MaxLength(100)]
        public string Subject { get; set; }
        [Required]
        [MaxLength(50)]
        public string Client { get; set; }
        public DateTimeOffset Issued { get; set; }
        public DateTimeOffset Expires { get; set; }
        [Required]
        public string ProtectedTicket { get; set; }
        public virtual ConnectionSource ConnectionSource { get; set; }
    }
    public class ConnectionSource {
        [Key]
        public string Id { get; set; }
        public string OS { get; set; }
        public string UserAgent { get; set; }
        public string Device { get; set; }
        public string RemoteIp { get; set; }
    }
}

namespace api.Models.JsonApi {
    public class RefreshTokenResource : ApiResource {
        public RefreshTokenResource() {
            Attribute("Client");
            Attribute("Issued");
            Attribute("Expires");
            BelongsTo<ConnectionSourceResource>("ConnectionSource");
        }
    }
    public class ConnectionSourceResource : ApiResource {
        public ConnectionSourceResource() {
            Attribute("OS");
            Attribute("UserAgent");
            Attribute("Device");
            Attribute("RemoteIp");
        }
    }
}
```
What's missing here? Thanks.

**Comment by rhyek** [comment]
So I made the changes necessary to get this working and made a pull request: #110. Also modified the `HandlesRecursiveProperties` test.

**Comment by dhirajdhakal09** [comment]
Hi rhyek,

i am new to github, perhaps it might not be a place to discuss, please spare me for that. 
Actually i am not able to generate the output with having data in relationship section and included members. I can only see the link in the relationship section. 

I had installed Saule using this command Install-Package saule as mentioned in the github, and this package does not have paging implementation either.

I have tried some of the url in the jsonapi.org like filtering the attributes, paging but none of them work. 

Below is how my Resources are arranged:

    public class NumberResource : ApiResource
    {
        public NumberResource()
        {
            OfType("numbers");
            Attribute("Number");

            BelongsTo<ServiceNumberPlanResource>("plans");
        }
    }

    public class PlanResource : ApiResource
    {
        public PlanResource()
        {
            OfType("plans");
            Attribute("Description");
        }

    }

Din't I download the correct version or what should i do in order to download the correct version of Saule? Please help me its too urgent.

**Comment by jrexdepew** [comment]
@dhirajdhakal09 the code that you have provided does not really go completely into the issue you are describing. The saule api resource definitions help the serializer know what the output of the object should look like but for them to work your model objects need to actually have nested data in them. Are you using entity framework? If so you can use the include function(https://msdn.microsoft.com/en-us/library/bb738708(v=vs.110).aspx) to retrieve a compound object and then saule should handle the output formating.  In regards to the jsonapi spec, saule(at least when I was using it) only implements some of the translation of the json api spec. If you want your web api code to support things like paging and filtering you either need to return an iqueryable back to your controller or you will need to implement that logic yourself. I may not be answering your question but I don't know that I will be able to with the information you have given.

**Comment by dhirajdhakal09** [comment]
@jrexdepew Thanks for your quick response.

Yes I am using Entity framework, ok please have a look into my models too

public class Number
    {
public Guid? Id { get; set; }
public string Number {get; set; }
public Plan plan {get; set; }
}
public class Plan
{
public Guid? Id {get; set;}
public string Description {get;set;}
}

And you said regarding returning Iqueryable back, is it in the web api
controller itself like
IQuerable<Number> GetAll()
{
return new IQuerable<Number>();
}

Please let me know if I have to modify something in order to have all the
elements back.

Thanks in advance.

**Comment by jrexdepew** [comment]
Your controller method code that you have should allow saule to append code to it for filtering and pagination.  If you want to test what saule is doing, you can just call the linq methods directly on your IQueryable.  To implement pagination, you would normally use the IQueryable skip and take methods(https://msdn.microsoft.com/en-us/library/bb357513(v=vs.100).aspx).  If you look at the example pagination code here: https://github.com/joukevandermaas/saule/wiki/Pagination you will see that the controller returns the IQueryable generic for a type of Person.  When you decorate your controller method with the attribute Paginate, then saule will just apply a linq query using the methods skip and take to the Person queryable collection.  Saule is able to perform this because IQueryable methods are usually chainable and will return IQueryable collections.

Now for the included objects, I would suggest testing returning an object that is nested that you have self created so that you can follow the code and know what is going on.  You can use object initializers to test this with something like:
`
public IQueryable<Number> MockupGetSomeNumbers()
{
  var myNumber = new Number{Id = new Guid(), 
                                                  Number = "12345", 
                                                  plan = new Plan{Id = new Guid(),
                                                                             Description = "Some Description"}};
 var someQueryableNumbers = new List<Number>();
 someQueryableNumbers.Add(myNumber);
 return someQueryableNumbers.AsQueryable();
}

[HttpGet]
[ReturnsResource(typeof(NumberResource))]
[Route("api/numbers"]
public IHttpActionResult GetSomeNumbers()
{
  return Ok(MockupGetSomeNumbers());
}
`

After writing that out it might be better to just use a linq select to return the iqueryable to test it but I will let you figure out how you would best like to do it.  Note: no guarantees that code will compile :)

Also if your question is general it may be better to open a new issue instead of posting on this enhancement issue.  I will leave that up to @joukevandermaas .  Hope that helps!

**Comment by dhirajdhakal09** [comment]
@jrexdepew  : Thanks for your reply, ya pagination now works, in the wiki, there is a typo where it says  to use **[Paginate(PerPage = 25)]**  which should be [Paginated(PerPage=25)] :) 

And I tried to run with the code you provided in order to return included columns, but doing that also din't help out, it is not returning included column yet.
This is what I got, 
{
  "data": [
    {
      "type": "numbers",
      "id": "00000000-0000-0000-0000-000000000000",
      "attributes": {
        "number": "12345",
      
      },
      "relationships": {

        "plans": {
          "links": {
            "self": "http://localhost:58739/api/numbers/00000000-0000-0000-0000-000000000000/relationships/plans/",
            "related": "http://localhost:58739/api/numbers/00000000-0000-0000-0000-000000000000/plans/"
          }
        }
      },
      "links": {
        "self": "http://localhost:58739/api/numbers/00000000-0000-0000-0000-000000000000/"
      }
    }
  ],
  "links": {
    "self": "http://localhost:58739/api/numbers"
  }
}

**Comment by dhirajdhakal09** [comment]
@jrexdepew  : Thanks for your reply, ya pagination now works, in the wiki, there is a typo where it says  to use **[Paginate(PerPage = 25)]**  which should be [Paginated(PerPage=25)] :) 

And I tried to run with the code you provided in order to return included columns, but doing that also din't help out, it is not returning included column yet.
This is what I got, 
{
  "data": [
    {
      "type": "numbers",
      "id": "00000000-0000-0000-0000-000000000000",
      "attributes": {
        "number": "12345",
      
      },
      "relationships": {

        "plans": {
          "links": {
            "self": "http://localhost:58739/api/numbers/00000000-0000-0000-0000-000000000000/relationships/plans/",
            "related": "http://localhost:58739/api/numbers/00000000-0000-0000-0000-000000000000/plans/"
          }
        }
      },
      "links": {
        "self": "http://localhost:58739/api/numbers/00000000-0000-0000-0000-000000000000/"
      }
    }
  ],
  "links": {
    "self": "http://localhost:58739/api/numbers"
  }
}

**Comment by dhirajdhakal09** [comment]
@jrexdepew : Did you get chance to look into my earlier message in this thread? Please help me its too urgent here :(

**Comment by joukevandermaas** [comment]
I just published a new pre-release with this functionality. Thanks very much, @rhyek!

**Comment by rhyek** [comment]
@joukevandermaas: No problem 👍
