### ISSUE TITLE
Serializing a resource with an id that includes a type prefix

### ISSUE THREAD

**Issue by corydeppen** [joukevandermaas/saule#63]
I'm looking at using Saule in an API that connects to a db with PK columns defined using a type + "Id" naming convention (e.g. ApplicationId). This doesn't work with Saule at the moment and returns a "Resources must have an id" error.

Have you considered allowing for the `id` property to be specified per model or applying a convention during serialization if an `id` property doesn't exist in the model?

**Comment by joukevandermaas** [comment]
Ah, I did not consider this. Since this is a convention from another framework/library, I'd rather not copy it as a convention into Saule. Before too long, there will be another convention and Saule will become a mess of hard to understand rules.

I'll add an API for this to `ApiResource`, so you can customize it.

**Comment by joukevandermaas** [comment]
I published a new prerelease with this functionality.

You can use the `WithId` function in the constructor of your resource:

```csharp
public class ApplicationResource : ApiResource
{
    public ApplicationResource()
    {
        OfType("Application");
        WithId(nameof(Application.ApplicationId));

        // ...
    }
}
```

I'll leave this issue open until I have added documentation for this feature.

**Comment by corydeppen** [comment]
Thanks for looking into this and pushing a release so quickly. Works well.

Re: Applying a convention - I had originally thought of something like Ember Data's [`primaryKey` property](http://emberjs.com/api/data/classes/DS.RESTSerializer.html#property_primaryKey), which might allow a consumer of Saule to override a serializer method with something like the following so that the `id` didn't need to be specified in each resource:

```
primaryKey: function(resourceType) {
  return resourceType + 'Id';
}
```
