### ISSUE TITLE
Self referencing loop detected

### ISSUE THREAD

**Issue by corydeppen** [joukevandermaas/saule#67]
I ran into a problem with my resources that reference each other, as seen below.

```
// ApplicationResource
BelongsTo<LevelResource>("Level");

// LevelResource
HasMany<ApplicationResource>("Applications");
```

The API is returning the data without an issue, but I get the following InvalidOperationException when an attempt is made to serialize the results:

```
"The 'ObjectContent`1' type failed to serialize the response body for content type 'application/vnd.api+json'. Self referencing loop detected with type 'Models.Application'. Path 'Level.Applications'."
```

If I remove the Applications collection from the Level object the results are serialized as expected. Prior to using Saule, I got around this issue by setting the `ReferenceLoopHandling` property on `JsonFormatter.SerializerSettings` to `ReferenceLoopHandling.Ignore`.

I wasn't sure if this was related to #18 or if it's something else.

**Comment by joukevandermaas** [comment]
#18 was something else; the app would crash at startup time. This looks like an issue with the way Saule uses Json.Net. I think it might be safe to always set that option (`ReferenceLoopHandling.Ignore`), but I'll have to investigate.

Thanks for reporting this.

**Comment by joukevandermaas** [comment]
I published a pre-release that should support this use-case. Since JSON API doesn't allow for recursion anyway, it's safe to always set this option to `Ignore` within Saule.

**Comment by corydeppen** [comment]
Works perfectly. Thanks again for the quick response.
