### ISSUE TITLE
Links generated with inconsistent base URL

### ISSUE THREAD

**Issue by corydeppen** [joukevandermaas/saule#71]
I've noticed that the `self` link in the top-level `links` object is the only one with the correct base URL. All URLs in other `links` objects use `localhost` as the base URL instead of the correct path to my API. If I specify the prefix in the `DefaultUrlPathBuilder` constructor all links are generated correctly. I'm confused why it would generate links and strip off two path segments from the URL.

**Comment by joukevandermaas** [comment]
It looks like this is a documentation issue and an internal inconsistency. 

Saule allows you to customize how URLs are generated from the path onwards. This means we can't guess which parts of the request URL are 'fixed' without potentially breaking someone's customization. We decided that consistency and predictability was preferable to guessing right some of the time. The prefix allows you to specify these fixed parts if you need them. 

However, the top level `self` link is still just the exact request URL. This is an inconsistency that should be fixed.

I think the documentation should explain why things work the way they do and the inconsistent behavior should be fixed. 

Thanks for reporting this.

**Comment by joukevandermaas** [comment]
I pushed a pre-release that makes the `prefix` parameter in the `DefaultUrlPathBuilder` unneeded in a lot of cases. This *only* works if you don't supply a path builder at all; if you do `new JsonApiConfiguration { UrlPathBuilder = new DefaultUrlPathBuilder() }` it will not work.

**Comment by corydeppen** [comment]
I updated the package but still see the same behavior - the top-level `self` link is the only one with a base URL matching the virtual path for the app (`/admin/api/v2`). As before, I can specify the prefix and all links are as I'd expect. I just wanted to make sure I'm using this as designed.

```
config.ConfigureJsonApi(new JsonApiConfiguration
{
  UrlPathBuilder = new DefaultUrlPathBuilder("/admin/api/v2")
});
```

**Comment by joukevandermaas** [comment]
What does the rest of your set up look like? Saule's unit tests might [implicitly assume](https://github.com/joukevandermaas/saule/blob/master/Tests/Helpers/NewSetupJsonApiServer.cs#L34) you use `MapAttributeRoutes`. Also see [this](https://github.com/joukevandermaas/saule/blob/master/Tests/Helpers/NewSetupJsonApiServer.cs#L34) integration test and the [related controller](https://github.com/joukevandermaas/saule/blob/0b2df35241c77495de65b72ede497293a1348834/Tests/Controllers/PeopleController.cs).

If you do use convention based routing, that might explain the difference. For now I'll reopen the issue.

Either way I haven't gotten round to updating the documentation, but it *should* work as follows:

* If you provide no `UrlPathBuilder` to the configuration object (`config.ConfigureJsonApi()`), Saule should figure out the virtual path for your app. This works because the default value for the `UrlPathBuilder` property is `null`.
* If you do provide a `UrlPathBuilder` (even the default one), Saule will assume it knows about your api and it won't try to find the virtual path.

**Comment by corydeppen** [comment]
I use both `MapHttpRoute` to support a dynamic route and `MapHttpAttributeRoutes` to support attribute routing in the controllers with `RoutePrefix` (resource type, so all methods don't need to include it) and `Route` attributes like your controller example uses. I also tried passing `new DefaultDirectRouteProvider()` as an arg to `MapHttpAttributeRoutes` as your integration test shows, but I saw the same behavior as before. The only thing that generates links as I'd expect right now is specifying a prefix in the `DefaultUrlPathBuilder`.

**Comment by joukevandermaas** [comment]
I've tried to come up with a more comprehensive test for this feature. The unit tests now cover [most possible template types](https://github.com/joukevandermaas/saule/blob/876697eb1e1936bf8c224af90ddd882db5027f43/Tests/Serialization/DefaultUrlPathBuilderTests.cs#L34) as far as I could tell. It seems like Web API automatically concatenates the `RoutePrefix` to the template. Some of these were indeed failing. I pushed a pre-release that passes all those tests.

If this doesn't solve your specific issue, I'd like to see a sample project with the minimal setup that surfaces the bug. I've tried many combinations of `MapHttpRoute`, `MapHttpAttributeRoutes` and `RoutePrefix`, and it seemed to work after these changes (#77).

Thanks again for reporting this and helping me track down the issue.

**Comment by corydeppen** [comment]
I looked through one of your tests and see one difference that may be causing my issue. As you'll see, the route's `template` parameter doesn't actually contain the resource name - it's empty for `GetApplications` and only contains the `id` parameter for `GetApplicationById`. The resource type is actually specified in the `RoutePrefix`. The segments being dropped in all cases but the `links` property is the IIS virtual path (`/admin/api/v2`), which is currently not specified anywhere in configuration unless I opt to use `new DefaultUrlPathBuilder("/admin/api/v2")`.

```csharp
[ReturnsResource(typeof(ApplicationResource))]
[RoutePrefix("applications")]
public class ApplicationsController : ApiController
{
    [Route("", Name = RouteNames.GetApplications)]
    public IEnumerable<Application> GetApplications()
    {
    }

    [Route("{id:int}", Name = RouteNames.GetApplicationById)]
    public Application GetApplicationById(int id)
    {
    }
}
```

**Comment by joukevandermaas** [comment]
As far as I've been able to tell, it is not possible to customize the virtual path root for an in-process OWIN test server, so I can't verify that the behavior is now correct in the tests. That said, I updated the code to read the property and prefix it. Hopefully that fixes the issue, even though I haven't been able to verify it properly.

Even if the most recent pre-release does not fix your problem, I will close this issue. I don't think there is more information available to Saule to make this work if it still doesn't. Thanks again for your help in trying to track down the bugs.

**Comment by corydeppen** [comment]
I don't know what version is responsible for resolving the issue I was seeing, but I just updated to 1.5.0.281-beta and the links at each level are now correct. I want to thank you and mention that I appreciate your hard work on this library.
