### ISSUE TITLE
Configurable casing when configuring Saule

### ISSUE THREAD

**Issue by markwalsh-liverpool** [joukevandermaas/saule#82]
Hello again,

Is it possible to configure Saule to use a particular type of casing when returning JSON?

Currently it returns kebab cased properties but in order to be compatible with my current endpoints, my consumers require camel casing.

**Comment by joukevandermaas** [comment]
The spec [recommends](http://jsonapi.org/recommendations/#naming) kebab casing, so I just went with that as a rule.

You could try experimenting with `JsonConverters` from NewtonSoft to see if you can make this work. If not, we could try figure something out.

**Comment by markwalsh-liverpool** [comment]
I think we need a way of configuring this via JsonApiConfiguration in order to set an option for serialization to be used in the ApiResource class, what do you think?

**Comment by joukevandermaas** [comment]
I'm closing this for now. I won't have time to implement this feature. I'll happily merge a PR if someone wants to make that though.

**Comment by markwalsh-liverpool** [comment]
Okay, I understand I will PR if I have time.  We plan on integrating Saule in my workplace and I will PR this when and if we do.
