### ISSUE TITLE
GUIDs are not supported as IDs in included values, throws an IConvert exception

### ISSUE THREAD

**Issue by Wozbo** [joukevandermaas/saule#89]
How to reproduce:

Make a few resources.  One of them should be 1..* to another
The many side resource should have a GUID as Id.

Serialization fails and the service fails with a 500 error.

This works if I make the guid a string.

**Comment by joukevandermaas** [comment]
Thanks for reporting this! I'll take a look when I have some time, hopefully in the coming couple of weeks.

**Comment by NullVoxPopuli** [comment]
@Wozbo can you provide a test proving that guids aren't supported? I forked saule, and found that in the Test `Website` project, there is an action that makes a Guid: https://github.com/joukevandermaas/saule/blob/master/Website/Controllers/TestController.cs#L19

**Comment by eltjo-k** [comment]
This should be fixed if #96 is found acceptable. I had not noticed there was already an issue about this problem.

**Comment by joukevandermaas** [comment]
Fixed in #96. Thanks @eltjo-k!
