### ISSUE TITLE
How do I serialize manually?

### ISSUE THREAD

**Issue by NullVoxPopuli** [joukevandermaas/saule#92]
Rather than using `ReturnsResource`, is there a way I can use the serializer manually?

Like, Rails' Active Model Serializers has:

```ruby
SerializableResource.new(object, serializer: MyObjectTypeSerializer, adapter: :json_api).to_json
```

if there could be something similar for saule, I think that would solve the problem, of having to return things that aren't a successful `{Type}Resource` -- like, rendering an errors object when we get `DbEntityValidationException`:

maybe something like:

```csharp
        [HttpPost]
        [Route("engines/")]
        public HttpResponseWhateverThisIs Create([FromBody] JObject engineData)
        {
            try
            {
                var engine = CurrentUser.Engines.Create(engineData);
                var response = new SerializableResource(engine, typeof(EngineResource), status: 201);
                return response;
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException ex)
            {
                // TODO: how do we serialize these errors?
                var errors = ex.EntityValidationErrors;
                var response = new SerializableResource(errorcs, typeof(Saule.ErrorResource), status: 422);
                return response;
            }
        }
```

**Comment by joukevandermaas** [comment]
You can use `JsonApiSerializer<T>` for this. It will not return an Http response, but it is relatively trivial to create one. It will throw the same exceptions the normal serialization pipeline produces.
