### ISSUE TITLE
Automatic attributes by convention

### ISSUE THREAD

**Issue by Wozbo** [joukevandermaas/saule#94]
I have an idea for a feature that would benefit a lot of people.  I'd like attributes to be inferred automatically (by convention) and support attribute blacklisting.  This would be useful for models that have many fields/ possibly go through refactoring.

Something like:  
`PersonResource : ApiResource<Person>`

HasMany and Belongs to could be inferred by types that are also an APIResource.

@nullvoxpopuli

**Comment by joukevandermaas** [comment]
It was a deliberate decision not to support this for now. The idea of `ApiResource`s is to mirror your Ember Data models.

That said, I've been working on an internal refactoring that makes attribute detection an extension point. This should allow you to detect attributes in any way you like, including reflection.

**Comment by joukevandermaas** [comment]
I'm closing this for now. It is possible to implement this functionality if you really need it, but I don't think it goes well with the spirit of Saule.
