### ISSUE TITLE
Support transient resources

### ISSUE THREAD

**Issue by Wozbo** [joukevandermaas/saule#95]
Some resources are transient (AKA no backing database).  This usually occurs with something that does calculation and returns calculation data.  The routing for this tries to create a link to the item which won't exist because it is transient.  There should be a convention to specify that the request is NOT idempotent and that the routing should refer to the original route, possibly with the original params.

**Comment by joukevandermaas** [comment]
If you want to override the generated urls, you can do so by implementing `IUrlPathBuilder`. See [the documentation](https://github.com/joukevandermaas/saule/wiki/Generating-links) on this topic.
