### ISSUE TITLE
Run example error

### ISSUE THREAD

**Issue by hdqva** [joukevandermaas/saule#97]
Dear joukevandermaas,

I pull the github repository to local and run. But I have received error:
- Post method: No MediaTypeFormatter is available to read an object of type 'TestModel' from content with media type 'application/json'
- Get method : error 406 not allowed.

Please help me how to run the website example.

Thank you very much.

**Comment by joukevandermaas** [comment]
The website example is not in a great state at the moment. It was used previously to do manual testing, but the test coverage has improved a lot and it's no longer really needed for that purpose. Perhaps we should replace it by a more complete and up to date 'Example' project.

**Comment by hdqva** [comment]
Thanks
