### ISSUE TITLE
Object(s) are serialized to JSON before applying the resource attribute filters. (Huge problem unless a resource is detached)

### ISSUE THREAD

**Issue by NullVoxPopuli** [joukevandermaas/saule#99]
So, I have an EF object.

My issue is that in `ResourceSerializer`, this line exists:

``` csharp
var objectJson = JToken.FromObject(_value, serializer);
```

This traverses ALL the attributes and relationships on the EF object.

What should happen is that based on the defined attributes and relationships in the Resource, is that those should iterate over the object reflectively pulling the attributes and relationships off the object. So that way, we don't unnecessarily serialize a giant tree of things (especially if lazy loading is enabled (I know people frown on lazy loading, that's not a discussion for here))

/cc @wozbo

**Comment by joukevandermaas** [comment]
Yeah I agree, this is not the desired behavior. Sadly, it would be non-trivial to change it. Maybe you can reduce the size of your EF object until I get a chance to pick this up?

**Comment by NullVoxPopuli** [comment]
I'm working on a solution, too. I have pushed the branch, but am still
working on it

**Comment by joukevandermaas** [comment]
Awesome, thanks!

**Comment by rhyek** [comment]
Hello, gents. I also need this behavior for a new project I'm currently working on. Any idea when this might be implemented? Thanks!

**Comment by joukevandermaas** [comment]
@rhyek: @NullVoxPopuli has been doing some work in #103. I'm not sure of the status of this, but the build is currently failing so I cannot merge it.

**Comment by joukevandermaas** [comment]
Fixed in #149.
